name: "Build"
on:
  push:
  pull_request:
env:
    CARGO_TERM_COLOR: always
jobs:
    build-windows:
        name: Windows Build
        runs-on: windows-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-windows
            cancel-in-progress: true
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install Rust Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Build (release)
              run: cargo build --release --locked --target x86_64-pc-windows-msvc
              env:
                RUSTFLAGS: --remap-path-prefix C:\Users\runneradmin\.cargo=/cargo
            - name: Upload Build
              uses: actions/upload-artifact@v4
              with:
                name: Windows Build
                path: target/x86_64-pc-windows-msvc/release/auto-compressor.exe
    # build-linux:
    #     name: Linux Build
    #     runs-on: ubuntu-latest
    #     concurrency:
    #         group: ${{ github.workflow }}-${{ github.ref }}-linux
    #         cancel-in-progress: true
    #     steps:
    #         - name: Checkout Repository
    #           uses: actions/checkout@v4
    #         - name: Install Rust Toolchain
    #           uses: actions-rust-lang/setup-rust-toolchain@v1
    #           with:
    #             target: x86_64-unknown-linux-musl
    #         - name: Install cargo-zigbuild
    #           run: pip install cargo-zigbuild
    #         - name: Build (release)
    #           run: cargo zigbuild --release --locked --target x86_64-unknown-linux-musl
    #         - name: Upload Build
    #           uses: actions/upload-artifact@v4
    #           with:
    #             name: Linux Build
    #             path: target/x86_64-unknown-linux-musl/release/auto-compressor

